import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Header } from '../components/Header'
import Input from '../components/Input'
import styles from './home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Eduick | Find your best teacher</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.container__main}>

        <div className={styles.container__main__content}>
          <img src="/images/hero.svg" alt="hero" />
          <div>
            <h2>Find your</h2>
            <h1>BEST TEACHER</h1>
            <p>
              Whether you are a student trying to find your
              ideal private language teachers/tutors or a teacher
              trying to find great students for your customised
              private lessons!
            </p>

            <Input name="search" placeholder="Type here what are you looking for" />

            <TrasactionTypeContainer>

              <RadioBox
                type="button"
                onClick={() => setType('deposit')}
                isActive={type === 'deposit'}
                activeColor='green'
              >
                <img src={incomeImg} alt="Entrada" />
                <span>Entrada</span>
              </RadioBox>

              <RadioBox
                type="button"
                onClick={() => setType('withdraw')}
                isActive={type === 'withdraw'}
                activeColor='red'
              >
                <img src={outcomeImg} alt="Saída" />
                <span>Saída</span>
              </RadioBox>

            </TrasactionTypeContainer>
          </div>
        </div>



      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}

export default Home
